# midget package manifest

package: "ExampleMod" # package name
version: 1.0f # version

full_name: "example mod" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://example.com" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [
	"example trigger",
] # displays trigger warnings, if empty than does not show anything
