# midget package manifest

package: "VS" # package name
version: 0.23 # version

full_name: "Friday Night Funkin' ONLINE VS. [HANK UPDATE]" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "drive.google.com/u/0/uc?export=download&confirm=Spiz&id=1vZynlOG64VIY6EVhkAHL_CN5CtOvA5eY" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [] # displays trigger warnings, if empty than does not show anything
