# midget package manifest

package: "VSBobAndBosip" # package name
version: 1.12 # version

full_name: "VS Bob and Bosip" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://github.com/ash237/vs-Bob-and-Bosip/releases/download/V1.1.2/B.B.The.Expansion.Update.V1.1.2.zip" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [
	"anti boyfriend",
] # displays trigger warnings, if empty than does not show anything
