# midget package manifest

package: "DSide" # package name
version: 0.21 # version

full_name: "Friday Night Funkin' D-Side" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://gamebanana.com/dl/650691" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [] # displays trigger warnings, if empty than does not show anything
