# midget package manifest

package: "VSSlyDreamatch" # package name
version: 1.0 # version

full_name: "VS Sly 1.5: Dreamatch FULL WEEK" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://gamebanana.com/dl/611446" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [
	"anti boyfriend",
] # displays trigger warnings, if empty than does not show anything
