# midget package manifest

package: "SummerVacations" # package name
version: 1.0 # version

full_name: "Summer Vacations" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://gamebanana.com/dl/573171" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [
	"feet",
] # displays trigger warnings, if empty than does not show anything
