# midget package manifest

package: "VSBB" # package name
version: 1.0f # version

full_name: "FNF Big Brother mod" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://gamebanana.com/dl/612921" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [
	"emotional",
] # displays trigger warnings, if empty than does not show anything
