# midget package manifest

package: "VSYuanAnimation" # package name
version: 1.5 # version

full_name: "Fnf x Yuan animation" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://gamebanana.com/dl/626349" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [] # displays trigger warnings, if empty than does not show anything
