# midget package manifest

package: "VSSly" # package name
version: 1.2 # version

full_name: "VS Sly FULL WEEK" # full name

# direct download links
# leave empty if version does not exist
# NOTE: works only with *.zip archives

win_dl_link: "https://gamebanana.com/dl/622748" # windows download link, required

mac_dl_link: "" # mac download link

linux_dl_link: "" # linux download link

triggers: [
	"anti boyfriend",
] # displays trigger warnings, if empty than does not show anything
